package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseAdmuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Admuser extends BaseAdmuser<Admuser> {
	public static final Admuser dao = new Admuser().dao();
}
