package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	public static final Article dao = new Article().dao();
}
