package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseClick;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Click extends BaseClick<Click> {
	public static final Click dao = new Click().dao();
}
