package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseColumn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Column extends BaseColumn<Column> {
	public static final Column dao = new Column().dao();
}
