package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseSalt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Salt extends BaseSalt<Salt> {
	public static final Salt dao = new Salt().dao();
}
