package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseUserFocus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserFocus extends BaseUserFocus<UserFocus> {
	public static final UserFocus dao = new UserFocus().dao();
}
