package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseUserComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserComment extends BaseUserComment<UserComment> {
	public static final UserComment dao = new UserComment().dao();
}
