package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseUserCollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserCollect extends BaseUserCollect<UserCollect> {
	public static final UserCollect dao = new UserCollect().dao();
}
