package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseUserColumn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserColumn extends BaseUserColumn<UserColumn> {
	public static final UserColumn dao = new UserColumn().dao();
}
