package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setCreatTime(java.util.Date creatTime) {
		set("creatTime", creatTime);
		return (M)this;
	}
	
	public java.util.Date getCreatTime() {
		return get("creatTime");
	}

	public M setTags(java.lang.Integer tags) {
		set("tags", tags);
		return (M)this;
	}
	
	public java.lang.Integer getTags() {
		return getInt("tags");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public M setIsPermit(java.lang.Integer isPermit) {
		set("isPermit", isPermit);
		return (M)this;
	}
	
	public java.lang.Integer getIsPermit() {
		return getInt("isPermit");
	}

	public M setSContent(java.lang.String sContent) {
		set("s_content", sContent);
		return (M)this;
	}
	
	public java.lang.String getSContent() {
		return getStr("s_content");
	}

	public M setCUrlImg(java.lang.String cUrlImg) {
		set("c_url_img", cUrlImg);
		return (M)this;
	}
	
	public java.lang.String getCUrlImg() {
		return getStr("c_url_img");
	}

	public M setCUrl(java.lang.String cUrl) {
		set("c_url", cUrl);
		return (M)this;
	}
	
	public java.lang.String getCUrl() {
		return getStr("c_url");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}
	
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public M setArtCollect(java.lang.Integer artCollect) {
		set("art_collect", artCollect);
		return (M)this;
	}
	
	public java.lang.Integer getArtCollect() {
		return getInt("art_collect");
	}

}
