package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseColumn<M extends BaseColumn<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCountArticle(java.lang.Integer countArticle) {
		set("count_article", countArticle);
		return (M)this;
	}
	
	public java.lang.Integer getCountArticle() {
		return getInt("count_article");
	}

	public M setColName(java.lang.String colName) {
		set("col_name", colName);
		return (M)this;
	}
	
	public java.lang.String getColName() {
		return getStr("col_name");
	}

	public M setCountUserfocus(java.lang.Integer countUserfocus) {
		set("count_userfocus", countUserfocus);
		return (M)this;
	}
	
	public java.lang.Integer getCountUserfocus() {
		return getInt("count_userfocus");
	}

}
