package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClick<M extends BaseClick<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setClickN(java.lang.Integer clickN) {
		set("clickN", clickN);
		return (M)this;
	}
	
	public java.lang.Integer getClickN() {
		return getInt("clickN");
	}

	public M setComN(java.lang.Integer comN) {
		set("comN", comN);
		return (M)this;
	}
	
	public java.lang.Integer getComN() {
		return getInt("comN");
	}

}
