package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setComp(java.lang.String comp) {
		set("comp", comp);
		return (M)this;
	}
	
	public java.lang.String getComp() {
		return getStr("comp");
	}

	public M setComc(java.lang.String comc) {
		set("comc", comc);
		return (M)this;
	}
	
	public java.lang.String getComc() {
		return getStr("comc");
	}

	public M setComt(java.lang.String comt) {
		set("comt", comt);
		return (M)this;
	}
	
	public java.lang.String getComt() {
		return getStr("comt");
	}

	public M setComac(java.lang.String comac) {
		set("comac", comac);
		return (M)this;
	}
	
	public java.lang.String getComac() {
		return getStr("comac");
	}

	public M setComGN(java.lang.Integer comGN) {
		set("comGN", comGN);
		return (M)this;
	}
	
	public java.lang.Integer getComGN() {
		return getInt("comGN");
	}

	public M setComBN(java.lang.Integer comBN) {
		set("comBN", comBN);
		return (M)this;
	}
	
	public java.lang.Integer getComBN() {
		return getInt("comBN");
	}

}
