package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNoluser<M extends BaseNoluser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setNolname(java.lang.String nolname) {
		set("nolname", nolname);
		return (M)this;
	}
	
	public java.lang.String getNolname() {
		return getStr("nolname");
	}

	public M setPsw(java.lang.String psw) {
		set("psw", psw);
		return (M)this;
	}
	
	public java.lang.String getPsw() {
		return getStr("psw");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setIcon(java.lang.String icon) {
		set("icon", icon);
		return (M)this;
	}
	
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Boolean getEnable() {
		return get("enable");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}
	
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public M setBirthday(java.lang.String birthday) {
		set("birthday", birthday);
		return (M)this;
	}
	
	public java.lang.String getBirthday() {
		return getStr("birthday");
	}

	public M setArticlesum(java.lang.Integer articlesum) {
		set("articlesum", articlesum);
		return (M)this;
	}
	
	public java.lang.Integer getArticlesum() {
		return getInt("articlesum");
	}

	public M setDiscription(java.lang.String discription) {
		set("discription", discription);
		return (M)this;
	}
	
	public java.lang.String getDiscription() {
		return getStr("discription");
	}

	public M setFriendsLike(java.lang.Integer friendsLike) {
		set("friends_like", friendsLike);
		return (M)this;
	}
	
	public java.lang.Integer getFriendsLike() {
		return getInt("friends_like");
	}

	public M setFriendsFans(java.lang.Integer friendsFans) {
		set("friends_fans", friendsFans);
		return (M)this;
	}
	
	public java.lang.Integer getFriendsFans() {
		return getInt("friends_fans");
	}

	public M setPhonenum(java.lang.String phonenum) {
		set("phonenum", phonenum);
		return (M)this;
	}
	
	public java.lang.String getPhonenum() {
		return getStr("phonenum");
	}

}
