package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdmuser<M extends BaseAdmuser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAdmname(java.lang.String admname) {
		set("admname", admname);
		return (M)this;
	}
	
	public java.lang.String getAdmname() {
		return getStr("admname");
	}

	public M setPsw(java.lang.String psw) {
		set("psw", psw);
		return (M)this;
	}
	
	public java.lang.String getPsw() {
		return getStr("psw");
	}

}
